[package]
name = "async_telemetry_broker"
version = "0.1.0"
edition = "2024"
keywords = ["async", "broker"]
license = "Apache-2.0"
repository = "https://github.com/timyiu478/async-telemetry-broker"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7.19", features = ["codec", "rt"] }
bytes = "1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing = "0.1.44"
futures-util = "0.3.34"
